### ISSUE TITLE
Make commands collapsible

### ISSUE THREAD

**Issue by mdonath** [timmisset/omt-odt-plugin#51]
During editing it would be convenient to be able to collapse the commands in an OMT file.

For example, if I was editing `xyz`, it would be nice if I could get rid of the very long code in `abc` by collapsing that command. 
```
commands: |
  DEFINE COMMAND abc() => {
    # very long code
  }

  DEFINE COMMAND xyz() => {
    # very long code
  }
```

**Comment by timmisset** [comment]
Available in version 5.8, version is currently reviewed by IntelliJ.
You can download it directly using https://plugins.jetbrains.com/plugin/download?rel=true&updateId=160325. Drag the zip onto IntelliJ to install it.

**Comment by mdonath** [comment]
Works awesome!

**Comment by timmisset** [comment]
Please consider rating the plugin: https://plugins.jetbrains.com/plugin/15292-omt--odt-language
